// DO NOT EDIT!!!
// Code generated by go-generated-views
// Version: example
// Revision: example
// Build Date: example
// Built By: example

//go:build example
// +build example

package example

// BookAddView represents view for model Book
type BookAddView struct {
	ID          uint64 `json:"-,omitempty"`
	Name        string `binding:"required" json:"name"`
	Description string `json:"description"`
}

// BookGetView represents view for model Book
type BookGetView struct {
	ID          uint64 `binding:"required,gt=0" json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

// ToModel change pointer from BookAddView to Book
func (view *BookAddView) ToModel() *Book {
	return (*Book)(view)
}

// NewBookAddView change pointer from Book to BookAddView
func NewBookAddView(model *Book) *BookAddView {
	return (*BookAddView)(model)
}

// ToModel change pointer from BookGetView to Book
func (view *BookGetView) ToModel() *Book {
	return (*Book)(view)
}

// NewBookGetView change pointer from Book to BookGetView
func NewBookGetView(model *Book) *BookGetView {
	return (*BookGetView)(model)
}
